user root;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /usr/local/nginx/conf/mime.types;
    default_type  application/octet-stream;

    ssl_session_timeout  20m;                         # 会话缓存超时时间为20分钟

    client_max_body_size 20G;                         # 最大允许上传的文件大小

    server {
        listen 80;
        server_name localhost;

        # WebDAV 数据目录
        location / {
            root /data/dav;  # 数据目录路径
            dav_methods PUT DELETE MKCOL COPY MOVE;
            dav_ext_methods PROPFIND OPTIONS;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;

            # 启用 Basic Auth
            auth_basic "Restricted Area";
            auth_basic_user_file /usr/local/nginx/conf/.htpasswd;

            # 启用目录浏览（可选）
            autoindex on;
            autoindex_exact_size off;
        }
    }
}