version: '3.8'

services:
  godev:
    image: crpi-p2k20xc75i1dtww9.cn-guangzhou.personal.cr.aliyuncs.com/hank997/godev:1.26.3
    container_name: godev
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - ./workspace:/home/normaluser/workspace
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
